/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import Controller.BookingPanel;
import Controller.CustomerPanel;
import Controller.NewJFrameLogIn;
import Controller.WorkerPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class NewJHotel1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJHotel1
     */
    
    GridBagLayout layout = new GridBagLayout();
    NewJPanelAll jPanelAll ;
    NewJPanel tablePanel;
    WorkerPanel workerPanel;
    CustomerPanel customerPanel;
    BookingPanel bookingPanel;
    public NewJHotel1() {
        initComponents();
//        workerinit();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jPanelAll = new NewJPanelAll();
        tablePanel = new NewJPanel();
        workerPanel= new WorkerPanel();
        customerPanel = new CustomerPanel();
        bookingPanel = new BookingPanel();
        MainPanel.setLayout(layout);
        GridBagConstraints con = new GridBagConstraints();
        con.gridx = 0;
        con.gridy = 0 ;
        MainPanel.add(jPanelAll,con);
         con.gridx = 0;
        con.gridy = 0 ;
        MainPanel.add(tablePanel,con);
        con.gridx = 0;
        con.gridy = 0 ;
        MainPanel.add(workerPanel,con);
        con.gridx = 0;
        con.gridy = 0 ;
        MainPanel.add(customerPanel,con);
        con.gridx = 0;
        con.gridy = 0 ;
        MainPanel.add(bookingPanel,con);
        jPanelAll.setVisible(true);
        tablePanel.setVisible(false);
        workerPanel.setVisible(false);
        customerPanel.setVisible(false);
        bookingPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboBoxAll = new javax.swing.JComboBox<>();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jComboBoxAll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Room", "Worker", "Customer", "Booking" }));
        jComboBoxAll.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBoxAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAllActionPerformed
        if(jComboBoxAll.getSelectedIndex() == 0){
            jPanelAll.setVisible(true);
            workerPanel.setVisible(false);
            tablePanel.setVisible(false);
            customerPanel.setVisible(false);
            bookingPanel.setVisible(false);
        }
        else if(jComboBoxAll.getSelectedIndex() == 1){
            
            jPanelAll.setVisible(false);
            workerPanel.setVisible(false);
            tablePanel.setData();
            tablePanel.setVisible(true);
            customerPanel.setVisible(false);
            bookingPanel.setVisible(false);
        }
        else if(jComboBoxAll.getSelectedIndex() == 2){
            jPanelAll.setVisible(false);
            workerPanel.setData();
            workerPanel.setVisible(true);
            tablePanel.setVisible(false);
            customerPanel.setVisible(false);
            bookingPanel.setVisible(false);
        }
        else if(jComboBoxAll.getSelectedIndex() == 3){
            jPanelAll.setVisible(false);
            workerPanel.setVisible(false);
            tablePanel.setVisible(false);
            customerPanel.setData();
            customerPanel.setVisible(true);
            bookingPanel.setVisible(false);
        }
        else if(jComboBoxAll.getSelectedIndex() == 4){
            jPanelAll.setVisible(false);
            workerPanel.setVisible(false);
            tablePanel.setVisible(false);
            customerPanel.setVisible(false);
            bookingPanel.setData();
            bookingPanel.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxAllActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        NewJFrameLogIn jFrameStart = new Controller.NewJFrameLogIn();
        jFrameStart.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
          if(jPanelAll.isVisible()){
              jPanelAll.reset();
          }
          else if(bookingPanel.isVisible()){
              bookingPanel.reset();
          }
          else if(customerPanel.isVisible()){
              customerPanel.reset();
          }
          else if(workerPanel.isVisible()){
              workerPanel.reset();
          }
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJHotel1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxAll;
    // End of variables declaration//GEN-END:variables

    private void workerinit() {
//         buttonGroup2.add(jRadioButtonMale1);
//         buttonGroup2.add(jRadioButtonFemale1);
    }
}
